version: '3.1'

services: 
  
  traefik:
    image: traefik:v1.6-alpine
    restart: always
    ports:  
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - $PWD/registry.toml:/etc/traefik/traefik.toml
      - /etc/letsencrypt:/certs:ro
#      - $PWD/acme:/acme

#    networks:
#      - registry

#/opt/emqttd/etc

  registry.dhms.net:
    image: registry:2
    restart: always
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
      - REGISTRY_AUTH_HTPASSWD_PATH="/auth/htpasswd"
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/live/registry.dhms.net/fullchain.pem
      - REGISTRY_HTTP_TLS_KEY=/certs/live/registry.dhms.net/privkey.pem

    #ports:
    #  - 5000:5000
    volumes:
      - $PWD/auth:/auth
      - /etc/letsencrypt:/certs:ro
      - $PWD/registrydata:/var/lib/registry

  regaccess:
    image: hollychen503/regaccess:latest
    restart: always
    volumes:
      - $PWD/auth:/auth
    

#networks:
#  registry
